/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secure;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class signup1 extends javax.swing.JFrame {
Connection conn;
//ResultSet rs;
PreparedStatement pst;

    /**
     * Creates new form signup1
     */
    public signup1() {
        super("Login");
        initComponents();
        conn=Javaconnect.ConnecrDb();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        back = new javax.swing.JButton();
        answertxt = new javax.swing.JPasswordField();
        secque = new javax.swing.JComboBox<>();
        passwordtxt = new javax.swing.JPasswordField();
        nametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(59, 149, 208));
        jLabel1.setText("SignUp");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 20, 130, 51);

        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });
        getContentPane().add(usernametxt);
        usernametxt.setBounds(420, 130, 143, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 130, 69, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 170, 44, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 220, 67, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Security Question");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 260, 130, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Answer");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 300, 70, 17);

        signup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signup.setForeground(new java.awt.Color(0, 0, 204));
        signup.setText("Sign-up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(210, 380, 90, 23);

        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 204));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(590, 380, 61, 23);
        getContentPane().add(answertxt);
        answertxt.setBounds(420, 300, 143, 20);

        secque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your pet name?", "What is your favourite TV show?", "Which is your favourite holiday destination? " }));
        secque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secqueActionPerformed(evt);
            }
        });
        getContentPane().add(secque);
        secque.setBounds(420, 260, 143, 20);

        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        getContentPane().add(passwordtxt);
        passwordtxt.setBounds(420, 210, 143, 20);

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        getContentPane().add(nametxt);
        nametxt.setBounds(420, 170, 143, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/signup.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, 0, 810, 440);

        setSize(new java.awt.Dimension(818, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login ob=new login();
        ob.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
                // TODO add your handling code here:
                boolean flag=true;
                try{
                  String sql="insert into Account (Username,Name,Password,Sec_Q,Answer) values(?,?,?,?,?)";
                  
                  String Name=nametxt.getText();
                  String Username=usernametxt.getText();
                  String Password=passwordtxt.getText();
                  String Answer=answertxt.getText();
                  if(Name.equals("")){
                JOptionPane.showMessageDialog(null, "Name is Mandatory");
                flag=false;
            }
            if(Username.equals("")){
                JOptionPane.showMessageDialog(null, "Username Is Mandatory");
                flag=false;
            }
            if(Password.equals("")){
                JOptionPane.showMessageDialog(null, "Password Is Mandatory");
                flag=false;
            }
            if(Answer.equals("")){
                JOptionPane.showMessageDialog(null,"Answer Is Mandatory");
                flag=false;
            }
                 if(flag){
                  pst=conn.prepareStatement(sql);
                  pst.setString(1,usernametxt.getText());
                  pst.setString(2,nametxt.getText());
                  pst.setString(3,passwordtxt.getText());
                  pst.setString(4,(String) secque.getSelectedItem());
                  pst.setString(5,answertxt.getText());
                 
                  pst.executeUpdate();
                  JOptionPane.showMessageDialog(null, "NEW ACCOUNT CREATED!");
                  }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }finally{
                    try{
                           // rs.close();
                           if(flag){
                            pst.close();
                           }
                           }
                         catch(Exception e)
                        {
                            JOptionPane.showMessageDialog(null,"Thankyou");
                            e.printStackTrace();
                        }
        }
    }//GEN-LAST:event_signupActionPerformed

    private void secqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField answertxt;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JComboBox<String> secque;
    private javax.swing.JButton signup;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
