/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.HospitalPatient;
import Model.MainAdmin;
import UI.LabRequest.RequestLabTestJPanel;
import java.awt.CardLayout;
import java.util.Date;
import java.sql.Connection; // Corrected import for Connection
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.JPanel;


/**
 *
 * @author shrikrishnanayak
 */
public class CreateNewPatient extends javax.swing.JPanel {
    JPanel workArea;
    MainAdmin admin;
    /**
     * Creates new form CreateNewPatient
     */

    public CreateNewPatient(JPanel workArea, MainAdmin admin) {
        initComponents();
        this.workArea = workArea;
        this.admin = admin;
        populateDepartmentComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDepartment = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStaffPassword = new javax.swing.JLabel();
        txtPatName = new javax.swing.JTextField();
        txtPatAge = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtStaffPassword1 = new javax.swing.JLabel();
        txtStaffPassword2 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        txtStaffPassword3 = new javax.swing.JLabel();
        jGender = new javax.swing.JComboBox<>();
        txtStaffPassword4 = new javax.swing.JLabel();
        txtPatHistory = new javax.swing.JTextField();
        txtStaffPassword5 = new javax.swing.JLabel();
        txtStaffPassword6 = new javax.swing.JLabel();
        jAllergy = new javax.swing.JComboBox<>();
        jDoctor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        JBloodGroup = new javax.swing.JComboBox<>();
        txtStaffPassword7 = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        jDob = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("DEPARTMENT :");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("PATIENT NAME :");

        jDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepartmentActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("PATIENT AGE :");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("PATIENT DATE OF BIRTH :");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("PATIENT GENDER :");

        txtStaffPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword.setText("PATIENT ADDRESS :");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NEW PATIENT");

        txtStaffPassword1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword1.setText("PATIENT CONTACT :");

        txtStaffPassword2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword2.setText("PATIENT GMAIL :");

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        txtStaffPassword3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword3.setText("PATIENT BLOOG GROUP :");

        jGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));

        txtStaffPassword4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword4.setText("PATIENT MEDICAL HISTORY :");

        txtStaffPassword5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword5.setText("ALLERGY :");

        txtStaffPassword6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword6.setText("DOCTOR :");

        jAllergy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));

        txtStaffPassword7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword7.setText("REASON TO VISIT :");

        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton4)
                        .addGap(402, 402, 402)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStaffPassword2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(txtStaffPassword))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(txtStaffPassword1))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtContact)
                                .addComponent(txtAddress)
                                .addComponent(jGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatName)
                                .addComponent(txtPatAge)
                                .addComponent(txtGmail, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                            .addComponent(jDob, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStaffPassword4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtStaffPassword3)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPatHistory)
                                    .addComponent(JBloodGroup, 0, 265, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtStaffPassword5)
                                    .addComponent(txtStaffPassword7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtStaffPassword6)
                                        .addGap(11, 11, 11)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jAllergy, 0, 265, Short.MAX_VALUE)
                                    .addComponent(jDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDoctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtReason))))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStaffPassword3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(JBloodGroup))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStaffPassword4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtStaffPassword5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtStaffPassword6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jAllergy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReason, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStaffPassword7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPatName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPatAge, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStaffPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStaffPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (validateInput()) {
            String name = txtPatName.getText();
            String age = txtPatAge.getText();
            Date dob = jDob.getDate();
            String gender = (String) jGender.getSelectedItem();
            String address = txtAddress.getText();
            String contact = txtContact.getText();
            String email = txtGmail.getText();
            String bloodGroup = (String) JBloodGroup.getSelectedItem();
            String medicalHistory = txtPatHistory.getText();
            String allergy = (String) jAllergy.getSelectedItem();
            String department = (String) jDepartment.getSelectedItem();
            String doctor = (String) jDoctor.getSelectedItem();
            String reasonToVisit = txtReason.getText();

            HospitalPatient newPatient = new HospitalPatient(name, age, dob, gender, address, contact, email, bloodGroup, medicalHistory, allergy, department, doctor, reasonToVisit);

            insertPatientIntoDatabase(newPatient);
            clearFields();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepartmentActionPerformed
        String selectedDepartment = (String) jDepartment.getSelectedItem();
        if (selectedDepartment != null) {
            populateDoctorComboBox(selectedDepartment);
        }
    }//GEN-LAST:event_jDepartmentActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        HospitalStaffLanding hl =  new HospitalStaffLanding(workArea, admin);
        workArea.add("HospitalStaffLanding",hl);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JBloodGroup;
    private javax.swing.JComboBox<String> jAllergy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jDepartment;
    private com.toedter.calendar.JDateChooser jDob;
    private javax.swing.JComboBox<String> jDoctor;
    private javax.swing.JComboBox<String> jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtPatAge;
    private javax.swing.JTextField txtPatHistory;
    private javax.swing.JTextField txtPatName;
    private javax.swing.JTextField txtReason;
    private javax.swing.JLabel txtStaffPassword;
    private javax.swing.JLabel txtStaffPassword1;
    private javax.swing.JLabel txtStaffPassword2;
    private javax.swing.JLabel txtStaffPassword3;
    private javax.swing.JLabel txtStaffPassword4;
    private javax.swing.JLabel txtStaffPassword5;
    private javax.swing.JLabel txtStaffPassword6;
    private javax.swing.JLabel txtStaffPassword7;
    // End of variables declaration//GEN-END:variables
    private void insertPatientIntoDatabase(HospitalPatient patient) {
        Connection conn = null;
        PreparedStatement pst = null;

        try {
            conn = DriverManager.getConnection(admin.getDbUrl(), admin.getDbUsername(), admin.getDbPassword());
            String sql = "INSERT INTO Patients (name, age, dob, gender, address, contact, email, bloodGroup, medicalHistory, allergy, department, doctor, reasonToVisit) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(sql);

            pst.setString(1, patient.getName());
            pst.setString(2, patient.getAge());
            pst.setDate(3, new java.sql.Date(patient.getDob().getTime())); // Convert java.util.Date to java.sql.Date
            pst.setString(4, patient.getGender());
            pst.setString(5, patient.getAddress());
            pst.setString(6, patient.getContact());
            pst.setString(7, patient.getEmail());
            pst.setString(8, patient.getBloodGroup());
            pst.setString(9, patient.getMedicalHistory());
            pst.setString(10, patient.getAllergy());
            pst.setString(11, patient.getDepartment());
            pst.setString(12, patient.getDoctor());
            pst.setString(13, patient.getReasonToVisit());

            int result = pst.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Patient added successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to add patient.", "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void populateDepartmentComboBox() {
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            conn = DriverManager.getConnection(admin.getDbUrl(), admin.getDbUsername(), admin.getDbPassword());
            String sql = "SELECT department FROM Department"; // Adjust the column name and table name as per your database schema
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                jDepartment.addItem(rs.getString("department"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void populateDoctorComboBox(String department) {
        jDoctor.removeAllItems();
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            conn = DriverManager.getConnection(admin.getDbUrl(), admin.getDbUsername(), admin.getDbPassword());
            String sql = "SELECT name FROM Doctors WHERE department = ?"; // Adjust the column name and table name as per your database schema
            pst = conn.prepareStatement(sql);
            pst.setString(1, department);
            rs = pst.executeQuery();

            while (rs.next()) {
                jDoctor.addItem(rs.getString("name"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void clearFields() {
        txtPatName.setText("");
        txtPatAge.setText("");
        jDob.setDate(null);
        jGender.setSelectedIndex(0);
        txtAddress.setText("");
        txtContact.setText("");
        txtGmail.setText("");
        JBloodGroup.setSelectedIndex(0);
        txtPatHistory.setText("");
        jAllergy.setSelectedIndex(0);
        jDepartment.setSelectedIndex(0);
        jDoctor.removeAllItems(); // Clear doctor combo box
        txtReason.setText("");
    }
    
    private boolean validateInput() {
    // Validate Patient's Name
        if (txtPatName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter patient's name.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Patient's Age
        if (txtPatAge.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter patient's age.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Date of Birth
        if (jDob.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select patient's date of birth.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Patient's Gender
        if (jGender.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select patient's gender.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Address
        if (txtAddress.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter patient's address.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Contact
        if (txtContact.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter patient's contact number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Email
        if (txtGmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter patient's email.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Blood Group
        if (JBloodGroup.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select patient's blood group.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Medical History
        if (txtPatHistory.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter patient's medical history.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Allergy Information
        if (jAllergy.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select allergy information.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Department Selection
        if (jDepartment.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a department.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Doctor Selection
        if (jDoctor.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a doctor.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate Reason to Visit
        if (txtReason.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the reason for the visit.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    
        return true;
    }
}
