/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.MainAdmin;
import UI.LabRequest.RequestLabTestJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.sql.Connection; // Corrected import for Connection
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.JPanel;

/**
 *
 * @author shrikrishnanayak
 */
public class Doctor extends javax.swing.JPanel {
    private String username;
    JPanel workArea; 
    MainAdmin admin;
    /**
     * Creates new form Doctor
     */

    public Doctor(JPanel workArea, MainAdmin admin, String username ) {
        initComponents();
        this.workArea = workArea;
        this.admin = admin;
        this.username = username;
        populatePatientList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStaffPassword4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatHistory = new javax.swing.JTextField();
        txtStaffPassword = new javax.swing.JLabel();
        txtStaffPassword5 = new javax.swing.JLabel();
        txtPatAge = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtStaffPassword1 = new javax.swing.JLabel();
        txtStaffPassword7 = new javax.swing.JLabel();
        txtStaffPassword2 = new javax.swing.JLabel();
        txtReason = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStaffPassword3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPatName = new javax.swing.JComboBox<>();
        txtPatDob = new javax.swing.JTextField();
        txtPatGender = new javax.swing.JTextField();
        txtpatBloodGroup = new javax.swing.JTextField();
        txtPatAllergy = new javax.swing.JTextField();
        btnLab = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        txtStaffPassword4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword4.setText("PATIENT MEDICAL HISTORY :");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("PATIENT GENDER :");

        txtStaffPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword.setText("PATIENT ADDRESS :");

        txtStaffPassword5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword5.setText("ALLERGY :");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME DOCTOR.......");

        txtStaffPassword1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword1.setText("PATIENT CONTACT :");

        txtStaffPassword7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword7.setText("REASON TO VISIT :");

        txtStaffPassword2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword2.setText("PATIENT GMAIL :");

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("PATIENT NAME :");

        txtStaffPassword3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtStaffPassword3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtStaffPassword3.setText("PATIENT BLOOG GROUP :");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("PATIENT AGE :");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("PATIENT DATE OF BIRTH :");

        jPatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatNameActionPerformed(evt);
            }
        });

        btnLab.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLab.setText("REQUEST FOR LAB");
        btnLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setText("REQUEST MEDICINE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(btnLab, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStaffPassword2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(txtStaffPassword))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(txtStaffPassword1))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtContact)
                                        .addComponent(txtAddress)
                                        .addComponent(txtGmail, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                        .addComponent(jPatName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPatDob))
                                    .addComponent(txtPatAge, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtStaffPassword5)
                                        .addComponent(txtStaffPassword4)
                                        .addComponent(txtStaffPassword7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtStaffPassword3))))
                            .addComponent(txtPatGender, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPatHistory)
                            .addComponent(txtReason, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(txtpatBloodGroup)
                            .addComponent(txtPatAllergy))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStaffPassword3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(txtpatBloodGroup))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStaffPassword4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatAllergy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStaffPassword5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReason, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStaffPassword7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPatName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(txtPatAge))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatDob, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPatGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaffPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStaffPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void jPatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatNameActionPerformed
        String selectedPatientName = (String) jPatName.getSelectedItem();
        if (selectedPatientName != null) {
            updatePatientDetails(selectedPatientName);
        }
    }//GEN-LAST:event_jPatNameActionPerformed

    private void btnLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabActionPerformed
        String selectedPatientName = (String) jPatName.getSelectedItem();
        String patientContact = txtContact.getText();
        String patientGmail = txtGmail.getText();
        String doctorName = username;
        RequestLabTestJPanel lab = new RequestLabTestJPanel(workArea, admin, selectedPatientName, patientContact, patientGmail, doctorName);
        workArea.add("RequestLabTestJPanel",lab);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnLabActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selectedPatientName = (String) jPatName.getSelectedItem();
        String patientContact = txtContact.getText();
        String patientGmail = txtGmail.getText();
        String doctorName = username;
        PharmacyRequest pr = new PharmacyRequest(workArea, admin, selectedPatientName, patientContact, patientGmail, doctorName);
        workArea.add("PharmacyRequest",pr);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void populatePatientList() {
        try (Connection conn = DriverManager.getConnection(admin.getDbUrl(), admin.getDbUsername(), admin.getDbPassword());
             PreparedStatement pst = conn.prepareStatement(
                 "SELECT name, MAX(created_at) AS latest_entry FROM Patients WHERE doctor = ? GROUP BY name ORDER BY latest_entry DESC;")) {
            pst.setString(1, username);
            try (ResultSet rs = pst.executeQuery()) {
                while (rs.next()) {
                    jPatName.addItem(rs.getString("name"));
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLab;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jPatName;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtPatAge;
    private javax.swing.JTextField txtPatAllergy;
    private javax.swing.JTextField txtPatDob;
    private javax.swing.JTextField txtPatGender;
    private javax.swing.JTextField txtPatHistory;
    private javax.swing.JTextField txtReason;
    private javax.swing.JLabel txtStaffPassword;
    private javax.swing.JLabel txtStaffPassword1;
    private javax.swing.JLabel txtStaffPassword2;
    private javax.swing.JLabel txtStaffPassword3;
    private javax.swing.JLabel txtStaffPassword4;
    private javax.swing.JLabel txtStaffPassword5;
    private javax.swing.JLabel txtStaffPassword7;
    private javax.swing.JTextField txtpatBloodGroup;
    // End of variables declaration//GEN-END:variables
    
    private void updatePatientDetails(String patientName) {
        try (Connection conn = DriverManager.getConnection(admin.getDbUrl(), admin.getDbUsername(), admin.getDbPassword());
             PreparedStatement pst = conn.prepareStatement(
                 "SELECT * FROM Patients WHERE name = ? AND doctor = ? ORDER BY created_at DESC LIMIT 1")) {
            pst.setString(1, patientName);
            pst.setString(2, username);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    txtPatAge.setText(rs.getString("age"));
                    txtPatDob.setText(rs.getString("dob"));
                    txtPatGender.setText(rs.getString("gender"));
                    txtAddress.setText(rs.getString("address"));
                    txtContact.setText(rs.getString("contact"));
                    txtGmail.setText(rs.getString("email"));
                    txtpatBloodGroup.setText(rs.getString("bloodGroup"));
                    txtPatHistory.setText(rs.getString("medicalHistory"));
                    txtPatAllergy.setText(rs.getString("allergy"));
                    txtReason.setText(rs.getString("reasonToVisit"));
                    // Add more fields as required
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
