/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.HospitalStaff;
import Model.MainAdmin;
import UI.Lab.Staff.StaffLandingJPanel;
import UI.LabAdmin.LabAdminJPanel;
import UI.Pharmacy.PharmacyAdminJPanel;
import UI.Pharmacy.PharmacyLandingArea;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.sql.Connection; // Corrected import for Connection
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author shrikrishnanayak
 */
public class UI_Main extends javax.swing.JFrame {
    private MainAdmin admin;

    /**
     * Creates new form NewJFrame
     */
    public UI_Main(MainAdmin admin) {
        this.admin = admin;
   
        initComponents();
        setPreferredSize(new Dimension(1155, 748)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        jlbUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jlbPassword = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        workArea = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(250);

        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbUser.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jlbUser.setText("User :");
        controlPanel.add(jlbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 193, -1, 26));
        controlPanel.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 194, 138, 26));

        jlbPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jlbPassword.setText("Password :");
        controlPanel.add(jlbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 232, -1, 26));
        controlPanel.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 232, 138, 25));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        controlPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, 225, 56));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        controlPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 100, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2023-12-10 at 20.48.49.jpg"))); // NOI18N
        controlPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 800));

        jSplitPane1.setLeftComponent(controlPanel);

        workArea.setLayout(new java.awt.CardLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pexels-karolina-grabowska-4386467 (1).jpg"))); // NOI18N
        workArea.add(jLabel2, "card2");

        jSplitPane1.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = txtUser.getText();
        String password = new String(jPassword.getPassword());
        String userRole = validateLogin(username, password);

        if (userRole.equals("admin")) {
            JOptionPane.showMessageDialog(this, "Admin Login Successful!!!");
            Main_Landing mainLanding = new Main_Landing(workArea, admin);
            workArea.add("Main_Landing",mainLanding);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        } else if (userRole.equals("staff")) {
            JOptionPane.showMessageDialog(this, "Staff Login Successful!!!");
            HospitalStaffLanding hs = new HospitalStaffLanding(workArea, admin);
            workArea.add("HospitalStaffLanding",hs);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        } else if (userRole.equals("doctor")) {
            JOptionPane.showMessageDialog(this, "Doctor Login Successful!!!");
            Doctor doctorPage = new Doctor(workArea, admin, username); // Pass the username to the Doctor page
            workArea.add("Doctor", doctorPage);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        
        }   else if (userRole.equals("Lab_Admin")) {
            JOptionPane.showMessageDialog(this, "Admin Login Successful!!!");
            LabAdminJPanel labadminPage = new LabAdminJPanel(workArea, admin, username); // Pass the username to the Doctor page
            workArea.add("LabAdminLanding", labadminPage);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        } 
           else if (userRole.equals("Lab_Staff_Details")) {
            JOptionPane.showMessageDialog(this, "Staff Login Successful!!!");
            StaffLandingJPanel LabStaffPage = new StaffLandingJPanel(workArea, admin, username); // Pass the username to the Doctor page
            workArea.add("Lab_StaffLanding", LabStaffPage);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        
        }else if (userRole.equals("insurance")) {
            JOptionPane.showMessageDialog(this, "Insurance Login Successful!!!");
            InsuranceLandingPage insurancePage = new InsuranceLandingPage(workArea, admin); // Replace with your actual insurance landing panel
            workArea.add("InsuranceLandingJPanel", insurancePage);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        }else if (userRole.equals("pharmacy_admin")) {
            JOptionPane.showMessageDialog(this, "Pharmacy Admin Login Successful!!!");
            PharmacyAdminJPanel pharmacyadmin = new PharmacyAdminJPanel(workArea, admin, username); // Pass the username to the Doctor page
            workArea.add("PharmacyAdminJPanel", pharmacyadmin);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        }else if (userRole.equals("Pharmacy_Staff_Details")) {
            JOptionPane.showMessageDialog(this, "Pharmacy Staff Login Successful!!!");
            PharmacyLandingArea LandPage = new PharmacyLandingArea(workArea, admin, username); // Pass the username to the Doctor page
            workArea.add("PharmacyLandingArea", LandPage);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        
        }else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Failed", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainAdmin admin = new MainAdmin();
                new UI_Main(admin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbUser;
    private javax.swing.JTextField txtUser;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

    private String validateLogin(String username, String password) {
        if (checkCredentials("HospitalAdmin", username, password)) {
            return "admin";
        } else if (checkCredentials("HospitalStaff", username, password)) {
            return "staff";
        } else if (checkCredentials("Doctors", username, password)) {
            return "doctor"; // Fetch and return the doctor's name
        }else if(checkCredentialsLAB("Lab_Admin", username,password)){
                return "Lab_Admin";
        }else if(checkCredentialsLAB("Lab_Staff_Details", username,password)){
                return "Lab_Staff_Details";
        }else if (checkCredentials("Insurance", username, password)) {
            return "insurance";
        }else if(checkCredentialsLAB("pharmacy_admin", username,password)){
                return "pharmacy_admin";
        }else if(checkCredentialsLAB("Pharmacy_Staff_Details", username,password)){
                return "Pharmacy_Staff_Details";     
        }else {
            return "invalid";
        }
    }
    private boolean checkCredentials(String tableName, String username, String password) {
        try (Connection conn = DriverManager.getConnection(admin.getDbUrl(), admin.getDbUsername(), admin.getDbPassword());
             PreparedStatement pst = conn.prepareStatement("SELECT * FROM " + tableName + " WHERE name=? AND password=?")) {
            pst.setString(1, username);
            pst.setString(2, password);
            try (ResultSet rs = pst.executeQuery()) {
                return rs.next();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    private String getDoctorName(String username) {
        try (Connection conn = DriverManager.getConnection(admin.getDbUrl(), admin.getDbUsername(), admin.getDbPassword());
             PreparedStatement pst = conn.prepareStatement("SELECT name FROM Doctors WHERE name=?")) {
            pst.setString(1, username);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    return rs.getString("name");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return "";
    }
    
    
    private boolean checkCredentialsLAB(String tableName, String username, String password) {
        try (Connection conn = DriverManager.getConnection(admin.getDbUrl(), admin.getDbUsername(), admin.getDbPassword());
             PreparedStatement pst = conn.prepareStatement("SELECT * FROM " + tableName + " WHERE UserName=? AND Password=?")) {
            pst.setString(1, username);
            pst.setString(2, password);
            try (ResultSet rs = pst.executeQuery()) {
                return rs.next();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }
    
}
